name: dart_kalkulator_web
description: Kalkulator Dart versi web
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # kosong karena kita pakai Dart HTML

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4